#!/bin/sh

## Script to write in the config variables
## and copy the files to their install locations,
## using $PREFIX, $DESTDIR, $PYTHON from environment

: ${PREFIX:=/usr/local}
: ${DATADIR:=$PREFIX/share}
: ${BINDIR:=$PREFIX/bin}
: ${DBUSDIR=$DATADIR/dbus-1/services}
: ${DESTDIR:=}
: ${PYTHON:=$(which python)}
: ${INSTALL:=install -c}

set -e
exec >&2

DBINDIR=$DESTDIR$BINDIR
DDBUSDIR=$DESTDIR$DBUSDIR
DAPPDIR=$DESTDIR$DATADIR/applications

echo "Installing:"
echo "Binary: $DBINDIR"
echo "D-Bus services: $DDBUSDIR"
echo "Using python: $PYTHON"

## Make kzrnote
TMPNAME="kzrnote.$$"
echo "#!$PYTHON" > $TMPNAME
cat "kzrnote.py" | sed '/so .\/notemode.vim/ {
		r ./notemode.vim
		d  }' >> $TMPNAME
$INSTALL -v -D $TMPNAME "$DBINDIR/kzrnote"
rm -rf $TMPNAME

## Make the service file
SVC="se.kaizer.kzrnote.service"
TMPNAME="$SVC.$$"
sed -e "s_@BINDIR@_${BINDIR}_" $SVC.in > $TMPNAME
$INSTALL -v -m 644 -D $TMPNAME "$DDBUSDIR/$SVC"
rm -rf $TMPNAME

## kzrnote.desktop
$INSTALL -v -m 644 -D kzrnote.desktop "$DAPPDIR/kzrnote.desktop"

## kzrnote.svg
DICONDIR=$DESTDIR$DATADIR/icons/hicolor
DICONDEST=$DICONDIR/scalable/apps
$INSTALL -v -m 644 -D kzrnote.svg "$DICONDEST/scalable/apps/kzrnote.svg"
trap "gtk-update-icon-cache -q -f -t $DICONDIR" EXIT

type rsvg-convert >/dev/null || { echo "Skipping png icons, no rsvg-convert"; exit 0; }
## kzrnote.png from svg
for sz in 24 48 128
do
	T="kzrnote_$sz.png"
	rsvg-convert -w $sz -h $sz kzrnote.svg > $T
	$INSTALL -v -m 644 -D $T "$DICONDIR/${sz}x${sz}/apps/kzrnote.png"
	rm -f $T
done
